<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * The Elevate Global Trading electrical-appliance catalog, grouped by
     * category name. Every entry is a genuine, currently-or-recently-sold
     * model sourced from a Pakistani retailer or official manufacturer
     * listing (see `source` per product, kept here only for provenance —
     * not persisted to the database). `referencePrice` is the real market
     * price found at that source; `price` is the selling price shown on
     * the storefront, a flat 15% markup over the reference price rounded
     * to the nearest PKR 500. Product images are real photos downloaded
     * from the same source into public/images/products/, not hotlinked,
     * generated, or placeholder.
     */
    public function run(): void
    {
        // Replace the catalog wholesale rather than diffing it, so a
        // re-seed never leaves orphaned rows from a prior batch.
        Product::query()->delete();

        $catalog = [
            'Air Conditioners' => [
                [
                    'name' => 'Gree 36TFIH Floor Standing Inverter AC 3 Ton',
                    'skuCode' => 'GRE',
                    'brand' => 'Gree',
                    'model' => '36TFIH',
                    'referencePrice' => 609999.00,
                    'price' => 701500.00,
                    'short_description' => '3 Ton Gree floor standing inverter AC with G10 inverter technology, WiFi control, and heat & cool operation.',
                    'specifications' => ['Capacity' => '3 Ton', 'Type' => 'Floor Standing, DC Inverter', 'Mode' => 'Heat & Cool', 'Control' => 'WiFi-ready'],
                    'stock' => 3,
                    'featured' => true,
                    'imageFile' => 'gree-gf-36tfih-floor-standing-inverter-3-ton-ac.png',
                    'source' => 'shophive.com',
                ],
                [
                    'name' => 'Haier HBU-24HE/DC Cassette AC 2 Ton',
                    'skuCode' => 'HAI',
                    'brand' => 'Haier',
                    'model' => 'HBU-24HE/DC',
                    'referencePrice' => 454250.00,
                    'price' => 522500.00,
                    'short_description' => '2 Ton Haier 4-way ceiling cassette DC inverter AC with R410A refrigerant, built for premium commercial/residential spaces.',
                    'specifications' => ['Capacity' => '2 Ton', 'Type' => '4-Way Ceiling Cassette, DC Inverter', 'Refrigerant' => 'R410A', 'Rating' => '3-Star'],
                    'stock' => 3,
                    'featured' => true,
                    'imageFile' => 'haier-2-ton-ceiling-cassette-ac-hbu24hedc.jpg',
                    'source' => 'pakref.com',
                ],
                [
                    'name' => 'Kenwood e-Breeze KEB-2446FHI Floor Standing Inverter AC 2 Ton',
                    'skuCode' => 'KEN',
                    'brand' => 'Kenwood',
                    'model' => 'KEB-2446FHI',
                    'referencePrice' => 270000.00,
                    'price' => 310500.00,
                    'short_description' => '2 Ton Kenwood e-Breeze floor standing cabinet AC with twin rotary DC inverter compressor and heat & cool mode.',
                    'specifications' => ['Capacity' => '2 Ton', 'Type' => 'Floor Standing, DC Inverter', 'Compressor' => 'Twin Rotary', 'Mode' => 'Heat & Cool'],
                    'stock' => 4,
                    'featured' => false,
                    'imageFile' => 'kenwood-keb-2446fhi-2-ton-e-breeze-floor-standing-inverter-ac.webp',
                    'source' => 'electromart.com.pk',
                ],
                [
                    'name' => 'Dawlance Glamour 45 Floor Standing Inverter AC 2 Ton',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => 'Glamour 45 FS',
                    'referencePrice' => 373200.00,
                    'price' => 429000.00,
                    'short_description' => '2 Ton Dawlance Glamour floor standing inverter AC with gold-fin condenser coil and reversible inverter compressor.',
                    'specifications' => ['Capacity' => '2 Ton', 'Type' => 'Floor Standing, DC Inverter', 'Coil' => 'Gold Fin Condenser'],
                    'stock' => 3,
                    'featured' => true,
                    'imageFile' => 'dawlance-glamour-2-ton-inverter-floor-standing-ac.webp',
                    'source' => 'almumtaz.com.pk',
                ],
                [
                    'name' => 'Hisense Floor Standing Inverter AC 2 Ton',
                    'skuCode' => 'HIS',
                    'brand' => 'Hisense',
                    'model' => '24UR4RJJ1',
                    'referencePrice' => 250000.00,
                    'price' => 287500.00,
                    'short_description' => '2 Ton Hisense floor standing inverter AC using R32 refrigerant for efficient large-room cooling.',
                    'specifications' => ['Capacity' => '2 Ton', 'Type' => 'Floor Standing, DC Inverter', 'Refrigerant' => 'R32'],
                    'stock' => 4,
                    'featured' => false,
                    'imageFile' => 'hisense-floor-standing-ac-inverter-2-0-ton-24ur4rjj1.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'PEL Presimo T3 Inverter AC 2 Ton',
                    'skuCode' => 'PEL',
                    'brand' => 'PEL',
                    'model' => 'Presimo T3',
                    'referencePrice' => 199000.00,
                    'price' => 229000.00,
                    'short_description' => '2 Ton PEL Presimo T3 split inverter AC with R32 refrigerant and heat & cool operation.',
                    'specifications' => ['Capacity' => '2 Ton', 'Type' => 'Split, DC Inverter', 'Refrigerant' => 'R32', 'Mode' => 'Heat & Cool'],
                    'stock' => 5,
                    'featured' => false,
                    'imageFile' => 'pel-presimo-t3-inverter-ac-2-ton.webp',
                    'source' => 'hcsupermart.com',
                ],
                [
                    'name' => 'Orient Ultron EVA eComfort Inverter AC 1.5 Ton',
                    'skuCode' => 'ORI',
                    'brand' => 'Orient',
                    'model' => 'Ultron EVA',
                    'referencePrice' => 185000.00,
                    'price' => 213000.00,
                    'short_description' => '1.5 Ton Orient Ultron EVA eComfort DC inverter AC, T3 tropicalized for extreme heat, WiFi-ready.',
                    'specifications' => ['Capacity' => '1.5 Ton', 'Type' => 'Split, DC Inverter', 'Build' => 'T3 Tropicalized', 'Control' => 'WiFi-ready'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'orient-ultron-eva-ecomfort-metallic-1-5-ton-dc-inverter-ac.webp',
                    'source' => 'almumtaz.com.pk',
                ],
                [
                    'name' => 'TCL Floor Standing Inverter AC 2 Ton TAC-24T3-FH',
                    'skuCode' => 'TCL',
                    'brand' => 'TCL',
                    'model' => 'TAC-24T3-FH',
                    'referencePrice' => 285000.00,
                    'price' => 328000.00,
                    'short_description' => '2 Ton TCL floor standing inverter AC with heat & cool operation, gold fin condenser, and AI inverter technology.',
                    'specifications' => ['Capacity' => '2 Ton', 'Type' => 'Floor Standing, DC Inverter', 'Mode' => 'Heat & Cool', 'Cooling Capacity' => '24000 BTU'],
                    'stock' => 4,
                    'featured' => false,
                    'imageFile' => 'tcl-floor-standing-ac-inverter-2-0-ton-tac-24t3-fh.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
            ],
            'LED TVs' => [
                [
                    'name' => 'Samsung 65-inch 4K UHD Smart QLED TV Q6FN',
                    'skuCode' => 'SAM',
                    'brand' => 'Samsung',
                    'model' => '65Q6FN',
                    'referencePrice' => 237990.00,
                    'price' => 273500.00,
                    'short_description' => '65-inch Samsung QLED 4K UHD Smart TV with vivid color and sharp detail for a premium home viewing experience.',
                    'specifications' => ['Screen Size' => '65"', 'Panel' => 'QLED', 'Resolution' => '4K UHD'],
                    'stock' => 4,
                    'featured' => true,
                    'imageFile' => 'samsung-65-inch-4k-uhd-smart-qled-tv-65q6fn.webp',
                    'source' => 'priceoye.pk',
                ],
                [
                    'name' => 'LG UQ9100 55-inch 4K UHD Smart TV',
                    'skuCode' => 'LG',
                    'brand' => 'LG',
                    'model' => 'UQ9100',
                    'referencePrice' => 199999.00,
                    'price' => 230000.00,
                    'short_description' => '55-inch LG UQ9100 4K UHD Smart TV powered by the α5 Gen5 AI Processor for sharp upscaling and smart features.',
                    'specifications' => ['Screen Size' => '55"', 'Panel' => 'LED', 'Resolution' => '4K UHD', 'Processor' => 'α5 Gen5 AI'],
                    'stock' => 5,
                    'featured' => true,
                    'imageFile' => 'lg-led-uq9100-55-inch-4k-smart-tv.jpg',
                    'source' => 'islamabadelectronics.com',
                ],
                [
                    'name' => 'TCL C815 55-inch 4K QLED TV',
                    'skuCode' => 'TCL',
                    'brand' => 'TCL',
                    'model' => 'C815',
                    'referencePrice' => 176000.00,
                    'price' => 202500.00,
                    'short_description' => '55-inch TCL C815 QLED 4K TV with rich color depth and contrast for movies and sports.',
                    'specifications' => ['Screen Size' => '55"', 'Panel' => 'QLED', 'Resolution' => '4K'],
                    'stock' => 5,
                    'featured' => true,
                    'imageFile' => 'tcl-55-inch-4k-qled-tv-c815.webp',
                    'source' => 'priceoye.pk',
                ],
                [
                    'name' => 'Haier 65-inch 4K LED TV LE65U6900UG',
                    'skuCode' => 'HAI',
                    'brand' => 'Haier',
                    'model' => 'LE65U6900UG',
                    'referencePrice' => 149999.00,
                    'price' => 172500.00,
                    'short_description' => '65-inch Haier 4K LED Smart TV offering a large-screen viewing experience at everyday value.',
                    'specifications' => ['Screen Size' => '65"', 'Panel' => 'LED', 'Resolution' => '4K'],
                    'stock' => 5,
                    'featured' => false,
                    'imageFile' => 'haier-65-inch-4k-led-tv-le65u6900ug.webp',
                    'source' => 'priceoye.pk',
                ],
                [
                    'name' => 'Orient Titanium 55T QLED TV',
                    'skuCode' => 'ORI',
                    'brand' => 'Orient',
                    'model' => '55T',
                    'referencePrice' => 130000.00,
                    'price' => 149500.00,
                    'short_description' => '55-inch Orient Titanium QLED 4K TV with HDR10, Dolby Audio, and Google TV built in.',
                    'specifications' => ['Screen Size' => '55"', 'Panel' => 'QLED', 'Resolution' => '4K', 'HDR' => 'HDR10', 'OS' => 'Google TV'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'orient-titanium-55t-qled-gray.jpg',
                    'source' => 'orient.com.pk',
                ],
                [
                    'name' => 'Samsung Crystal UHD DU7000 43-inch 4K Smart TV',
                    'skuCode' => 'SAM',
                    'brand' => 'Samsung',
                    'model' => 'UA43DU7000USWK',
                    'referencePrice' => 115000.00,
                    'price' => 132500.00,
                    'short_description' => '43-inch Samsung Crystal UHD 4K Smart TV running Tizen OS, with ALLM/VRR support for a responsive picture.',
                    'specifications' => ['Screen Size' => '43"', 'Panel' => 'LED', 'Resolution' => '4K', 'OS' => 'Tizen OS'],
                    'stock' => 7,
                    'featured' => false,
                    'imageFile' => 'samsung-43-inch-crystal-uhd-du7000-4k-smart-tv.png',
                    'source' => 'samsung.com/pk',
                ],
                [
                    'name' => 'Hisense 55U7A 55-inch 4K UHD Smart LED TV',
                    'skuCode' => 'HIS',
                    'brand' => 'Hisense',
                    'model' => '55U7A',
                    'referencePrice' => 106767.00,
                    'price' => 123000.00,
                    'short_description' => '55-inch Hisense 4K UHD Smart LED TV offering strong everyday value for a large-screen setup.',
                    'specifications' => ['Screen Size' => '55"', 'Panel' => 'LED', 'Resolution' => '4K UHD'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'hisense-55-inch-4k-uhd-smart-led-tv-55u7a.webp',
                    'source' => 'priceoye.pk',
                ],
            ],
            'Refrigerators' => [
                [
                    'name' => 'Haier 24 cu ft Side-by-Side Refrigerator HRF748KG',
                    'skuCode' => 'HAI',
                    'brand' => 'Haier',
                    'model' => 'HRF748KG',
                    'referencePrice' => 198000.00,
                    'price' => 227500.00,
                    'short_description' => '24 cu ft (688L) Haier side-by-side double door refrigerator for large households.',
                    'specifications' => ['Capacity' => '24 cu ft / 688L', 'Type' => 'Side-by-Side, Double Door'],
                    'stock' => 4,
                    'featured' => true,
                    'imageFile' => 'haier-24-cu-ft-sbs-series-hrf748kg.webp',
                    'source' => 'priceoye.pk',
                ],
                [
                    'name' => 'Haier 19 cu ft Side-by-Side Refrigerator HRF622IBG',
                    'skuCode' => 'HAI',
                    'brand' => 'Haier',
                    'model' => 'HRF622IBG',
                    'referencePrice' => 278600.00,
                    'price' => 320500.00,
                    'short_description' => '19 cu ft (550L) Haier side-by-side double door refrigerator with a premium glass finish.',
                    'specifications' => ['Capacity' => '19 cu ft / 550L', 'Type' => 'Side-by-Side, Double Door'],
                    'stock' => 3,
                    'featured' => false,
                    'imageFile' => 'haier-19-cu-ft-sbs-series-hrf622ibg.webp',
                    'source' => 'priceoye.pk',
                ],
                [
                    'name' => 'Dawlance DTM-7650 Inverter Glass Door Refrigerator with IoT',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => 'DTM-7650 Inv GD IOT',
                    'referencePrice' => 198300.00,
                    'price' => 228000.00,
                    'short_description' => 'Dawlance full no-frost double door refrigerator with SE inverter technology and WiFi/IoT control via the HomeWhiz app.',
                    'specifications' => ['Type' => 'Full No Frost, Double Door, Glass Door', 'Technology' => 'SE Inverter', 'Control' => 'WiFi/IoT (HomeWhiz)'],
                    'stock' => 4,
                    'featured' => true,
                    'imageFile' => 'dawlance-dtm-7650-inv-glass-door-iot.webp',
                    'source' => 'dawlance.com.pk',
                ],
                [
                    'name' => 'PEL Digitron Ultra Inverter Curved Glass Door Refrigerator',
                    'skuCode' => 'PEL',
                    'brand' => 'PEL',
                    'model' => 'PRDTUINVOCGD-22270',
                    'referencePrice' => 125900.00,
                    'price' => 145000.00,
                    'short_description' => 'PEL Digitron Ultra 408L refrigerator with an InverterOn BLDC compressor and curved glass door.',
                    'specifications' => ['Capacity' => '408L', 'Compressor' => 'InverterOn BLDC', 'Door' => 'Curved Glass Door'],
                    'stock' => 5,
                    'featured' => false,
                    'imageFile' => 'pel-digitron-ultra-inverter-curved-glassdoor-refrigerator-22270.jpg',
                    'source' => 'eshop.pel.com.pk',
                ],
                [
                    'name' => 'Dawlance 9193LF Chrome Pearl Copper Refrigerator',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => '9193LF',
                    'referencePrice' => 107300.00,
                    'price' => 123500.00,
                    'short_description' => 'Dawlance large-capacity double door refrigerator suited for families of 7-8, in a Chrome Pearl Copper finish.',
                    'specifications' => ['Type' => 'Double Door', 'Capacity' => 'Large (7-8 person household)', 'Finish' => 'Chrome Pearl Copper'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'dawlance-9193lf-chrome-pearl-copper.webp',
                    'source' => 'dawlance.com.pk',
                ],
            ],
            'Washing Machines' => [
                [
                    'name' => 'Samsung WD16T6500GVST Front Load Washing Machine 16kg',
                    'skuCode' => 'SAM',
                    'brand' => 'Samsung',
                    'model' => 'WD16T6500GVST',
                    'referencePrice' => 390000.00,
                    'price' => 448500.00,
                    'short_description' => '16kg Samsung front load washing machine with inverter technology and 10 wash programs for large households.',
                    'specifications' => ['Capacity' => '16kg', 'Type' => 'Front Load, Inverter', 'Programs' => '10'],
                    'stock' => 2,
                    'featured' => true,
                    'imageFile' => 'samsung-wd16t6500gvst-automatic-washing-machine-16-kg-inverter-technology.png',
                    'source' => 'aysonline.pk',
                ],
                [
                    'name' => 'Kenwood Fully Automatic Front Load Washing Machine KWM-10005FAF-DG',
                    'skuCode' => 'KEN',
                    'brand' => 'Kenwood',
                    'model' => 'KWM-10005FAF-DG',
                    'referencePrice' => 223000.00,
                    'price' => 256500.00,
                    'short_description' => '10kg Kenwood front load washing machine with inverter technology and 1400 RPM spin speed.',
                    'specifications' => ['Capacity' => '10kg', 'Type' => 'Front Load, Inverter', 'Spin Speed' => '1400 RPM'],
                    'stock' => 4,
                    'featured' => true,
                    'imageFile' => 'kenwood-fully-automatic-front-load-kwm-10005faf-dg.png',
                    'source' => 'kenwoodpakistan.pk',
                ],
                [
                    'name' => 'LG F4Y2VYPYJ Front Load Washing Machine 9kg',
                    'skuCode' => 'LG',
                    'brand' => 'LG',
                    'model' => 'F4Y2VYPYJ',
                    'referencePrice' => 209000.00,
                    'price' => 240500.00,
                    'short_description' => '9kg LG front load washing machine with Inverter Direct Drive motor for quiet, efficient washing.',
                    'specifications' => ['Capacity' => '9kg', 'Type' => 'Front Load', 'Motor' => 'Inverter Direct Drive', 'Programs' => '6'],
                    'stock' => 4,
                    'featured' => false,
                    'imageFile' => 'lg-f4y2vypyj-automatic-front-load-washing-machine-9kg-inverter-direct-drive.webp',
                    'source' => 'aysonline.pk',
                ],
                [
                    'name' => 'Haier HW100-BP12357S8 Automatic Washing Machine 10kg',
                    'skuCode' => 'HAI',
                    'brand' => 'Haier',
                    'model' => 'HW100-BP12357S8',
                    'referencePrice' => 162000.00,
                    'price' => 186500.00,
                    'short_description' => '10kg Haier front load washing machine with inverter motor, 15 wash programs, and a 63L drum.',
                    'specifications' => ['Capacity' => '10kg', 'Type' => 'Front Load, Inverter', 'Programs' => '15', 'Drum' => '63L'],
                    'stock' => 4,
                    'featured' => false,
                    'imageFile' => 'haier-hw100-bp12357s8-automatic-washing-machine-10-kg-inverter.webp',
                    'source' => 'aysonline.pk',
                ],
                [
                    'name' => 'Dawlance Front Load Washing Machine DWF 8120 GR INV',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => 'DWF 8120 GR INV',
                    'referencePrice' => 180000.00,
                    'price' => 207000.00,
                    'short_description' => '8kg Dawlance front load washing machine with a brushless inverter motor and 1200 RPM spin speed.',
                    'specifications' => ['Capacity' => '8kg', 'Type' => 'Front Load, Inverter', 'Spin Speed' => '1200 RPM', 'Rating' => 'A+++'],
                    'stock' => 5,
                    'featured' => false,
                    'imageFile' => 'dawlance-front-load-washing-machine-dwf-8120-gr-inv.webp',
                    'source' => 'dawlance.com.pk',
                ],
            ],
            'Dishwashers' => [
                [
                    'name' => 'Dawlance Dish Washer DDW-1470 GB',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => 'DDW-1470 GB',
                    'referencePrice' => 190000.00,
                    'price' => 218500.00,
                    'short_description' => 'Dawlance freestanding dishwasher with 14 place settings and an inverter motor.',
                    'specifications' => ['Capacity' => '14 Place Settings', 'Type' => 'Freestanding, Inverter'],
                    'stock' => 4,
                    'featured' => false,
                    'imageFile' => 'dawlance-ddw-1470-gb-dishwasher.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Samsung Dish Washer DW-60M5070FS',
                    'skuCode' => 'SAM',
                    'brand' => 'Samsung',
                    'model' => 'DW-60M5070FS',
                    'referencePrice' => 142900.00,
                    'price' => 164500.00,
                    'short_description' => 'Samsung freestanding dishwasher with 14 place settings and 7 wash programs.',
                    'specifications' => ['Capacity' => '14 Place Settings', 'Type' => 'Freestanding', 'Programs' => '7'],
                    'stock' => 4,
                    'featured' => false,
                    'imageFile' => 'samsung-dw-60m5070fs-dishwasher.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Dawlance Dish Washer DDW-868 CTB',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => 'DDW-868 CTB',
                    'referencePrice' => 78400.00,
                    'price' => 90000.00,
                    'short_description' => 'Dawlance countertop dishwasher with 8 place settings and an A+ energy rating — a compact option for smaller kitchens.',
                    'specifications' => ['Capacity' => '8 Place Settings', 'Type' => 'Countertop', 'Energy Rating' => 'A+'],
                    'stock' => 5,
                    'featured' => false,
                    'imageFile' => 'dawlance-ddw-868-ctb-dishwasher.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
            ],
            'Microwaves' => [
                [
                    'name' => 'Kenwood Microwave Oven MWP-31.010SI',
                    'skuCode' => 'KEN',
                    'brand' => 'Kenwood',
                    'model' => 'MWP-31.010SI',
                    'referencePrice' => 39000.00,
                    'price' => 45000.00,
                    'short_description' => '31L Kenwood solo microwave oven with 1000W output and 11 power levels.',
                    'specifications' => ['Capacity' => '31L', 'Type' => 'Solo', 'Power' => '1000W'],
                    'stock' => 7,
                    'featured' => false,
                    'imageFile' => 'kenwood-mwp-31-010si-microwave-oven.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Dawlance Microwave Oven DW-131 HP',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => 'DW-131 HP',
                    'referencePrice' => 34900.00,
                    'price' => 40000.00,
                    'short_description' => '30L Dawlance grill microwave oven with 900W output and digital controls.',
                    'specifications' => ['Capacity' => '30L', 'Type' => 'Grill', 'Power' => '900W'],
                    'stock' => 8,
                    'featured' => false,
                    'imageFile' => 'dawlance-dw-131-hp-microwave-oven.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Haier Microwave Oven HMW-20MX12',
                    'skuCode' => 'HAI',
                    'brand' => 'Haier',
                    'model' => 'HMW-20MX12',
                    'referencePrice' => 17500.00,
                    'price' => 20000.00,
                    'short_description' => '20L Haier solo microwave oven with 900W output and digital touch controls.',
                    'specifications' => ['Capacity' => '20L', 'Type' => 'Solo', 'Power' => '900W'],
                    'stock' => 9,
                    'featured' => false,
                    'imageFile' => 'haier-hmw-20mx12-microwave-oven.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Dawlance Microwave Oven DW-MD4',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => 'DW-MD4',
                    'referencePrice' => 15499.00,
                    'price' => 18000.00,
                    'short_description' => '20L Dawlance solo microwave oven with 700W output and simple mechanical controls.',
                    'specifications' => ['Capacity' => '20L', 'Type' => 'Solo', 'Power' => '700W', 'Control' => 'Mechanical'],
                    'stock' => 10,
                    'featured' => false,
                    'imageFile' => 'dawlance-dw-md4-microwave-oven.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
            ],
            'Electric Geysers' => [
                [
                    'name' => 'Beetro Fast Electric Geyser FFE-40',
                    'skuCode' => 'BEE',
                    'brand' => 'Beetro',
                    'model' => 'FFE-40',
                    'referencePrice' => 29000.00,
                    'price' => 33500.00,
                    'short_description' => '40L Beetro fast-heating electric geyser with an Incoloy 840 heating element for durability.',
                    'specifications' => ['Capacity' => '40L', 'Element' => 'Incoloy 840'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'beetro-ffe-40-electric-geyser.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Super Asia Electric Geyser SEH-15 Saver Series',
                    'skuCode' => 'SUP',
                    'brand' => 'Super Asia',
                    'model' => 'SEH-15',
                    'referencePrice' => 29000.00,
                    'price' => 33500.00,
                    'short_description' => '15L Super Asia semi-instant electric geyser from the Saver Series, built for efficient everyday use.',
                    'specifications' => ['Capacity' => '15L', 'Type' => 'Semi-Instant'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'super-asia-seh-15-electric-geyser.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Canon Electric Geyser EWT-30',
                    'skuCode' => 'CAN',
                    'brand' => 'Canon',
                    'model' => 'EWT-30',
                    'referencePrice' => 24900.00,
                    'price' => 28500.00,
                    'short_description' => '30L Canon electric geyser with a 2000W heating element and adjustable thermostat.',
                    'specifications' => ['Capacity' => '30L', 'Power' => '2000W', 'Control' => 'Adjustable Thermostat'],
                    'stock' => 7,
                    'featured' => false,
                    'imageFile' => 'canon-ewt-30-electric-geyser.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'NasGas Semi-Instant Electric Geyser SEM-200',
                    'skuCode' => 'NAS',
                    'brand' => 'NasGas',
                    'model' => 'SEM-200',
                    'referencePrice' => 23500.00,
                    'price' => 27000.00,
                    'short_description' => '20L NasGas semi-instant electric geyser with a 2000W element and dry-heat protection.',
                    'specifications' => ['Capacity' => '20L', 'Power' => '2000W', 'Protection' => 'Dry-Heat Protection'],
                    'stock' => 7,
                    'featured' => false,
                    'imageFile' => 'nasgas-sem-200-electric-geyser.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
            ],
            'Electrical Ovens' => [
                [
                    'name' => 'Westpoint Electric Oven WF-6300/6000RKC',
                    'skuCode' => 'WES',
                    'brand' => 'Westpoint',
                    'model' => 'WF-6300/6000RKC',
                    'referencePrice' => 37000.00,
                    'price' => 42500.00,
                    'short_description' => 'Westpoint 2200W electric oven with rotisserie and kebab/BBQ function for versatile home cooking.',
                    'specifications' => ['Power' => '2200W', 'Function' => 'Rotisserie, Kebab/BBQ'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'westpoint-wf-6300-6000rkc-electric-oven.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Westpoint Electric Oven WF-4711',
                    'skuCode' => 'WES',
                    'brand' => 'Westpoint',
                    'model' => 'WF-4711',
                    'referencePrice' => 35400.00,
                    'price' => 40500.00,
                    'short_description' => '50L Westpoint electric oven with 1800W output, rotisserie, and kebab/BBQ function.',
                    'specifications' => ['Capacity' => '50L', 'Power' => '1800W', 'Function' => 'Rotisserie, Kebab/BBQ'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'westpoint-wf-4711-electric-oven.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
                [
                    'name' => 'Dawlance Electric Oven DWMO-5222 CR',
                    'skuCode' => 'DAW',
                    'brand' => 'Dawlance',
                    'model' => 'DWMO-5222 CR',
                    'referencePrice' => 33000.00,
                    'price' => 38000.00,
                    'short_description' => '52L Dawlance electric oven with 2200W convection heating and a dual-glass door.',
                    'specifications' => ['Capacity' => '52L', 'Power' => '2200W', 'Type' => 'Convection', 'Door' => 'Dual-Glass'],
                    'stock' => 6,
                    'featured' => false,
                    'imageFile' => 'dawlance-dwmo-5222-electric-oven.webp',
                    'source' => 'umarelectronics.pk',
                ],
                [
                    'name' => 'Anex Oven Toaster AG-2070BB',
                    'skuCode' => 'ANE',
                    'brand' => 'Anex',
                    'model' => 'AG-2070BB',
                    'referencePrice' => 27910.00,
                    'price' => 32000.00,
                    'short_description' => '43L Anex convection oven toaster with a 2000W stainless steel heating element.',
                    'specifications' => ['Capacity' => '43L', 'Power' => '2000W', 'Type' => 'Convection', 'Element' => 'Stainless Steel'],
                    'stock' => 7,
                    'featured' => false,
                    'imageFile' => 'anex-ag-2070bb-oven-toaster.jpg',
                    'source' => 'japanelectronics.com.pk',
                ],
            ],
        ];

        foreach ($catalog as $categoryName => $products) {
            foreach ($products as $index => $product) {
                $category = Category::where('slug', Str::slug($categoryName))->first();

                if (! $category) {
                    continue;
                }

                $slug = Str::slug($product['name']);
                $imageFile = $product['imageFile'] ?? "{$slug}.".($product['imageExt'] ?? 'jpg');

                Product::updateOrCreate(
                    ['slug' => $slug],
                    [
                        'name' => $product['name'],
                        'sku' => $product['skuCode'].'-'.Str::upper(Str::substr($categoryName, 0, 3)).'-'.(1001 + $index),
                        'category_id' => $category->id,
                        'brand' => $product['brand'],
                        'price' => $product['price'],
                        'sale_price' => null,
                        'short_description' => $product['short_description'],
                        'description' => $product['short_description'].' Available now at '.config('business.name').'.',
                        'specifications' => $product['specifications'],
                        'stock' => $product['stock'],
                        'status' => true,
                        'featured' => $product['featured'],
                        'image' => "images/products/{$imageFile}",
                    ]
                );
            }
        }
    }
}
